const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(root, "app.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");

new vm.Script(source);

function rendererSource(name, nextName) {
  const start = source.indexOf(`function ${name}(`);
  const end = source.indexOf(`function ${nextName}(`, start);
  assert.notEqual(start, -1, `missing ${name}`);
  assert.notEqual(end, -1, `missing ${nextName}`);
  return source.slice(start, end);
}

const brief = rendererSource("renderBrief", "renderScan");
const scan = rendererSource("renderScan", "renderCheckpoint1");
const reflection = rendererSource("renderReflection", "getConceptReview");
const result = rendererSource("renderResult", "aggregateStudent");
const checkpoint1Catalog = source.slice(source.indexOf("const checkpoint1Items = ["), source.indexOf("const structureOptions", source.indexOf("const checkpoint1Items = [")));
const checkpoint1Ids = [...checkpoint1Catalog.matchAll(/id:\s*"([^"]+)"/g)].map((match) => match[1]);
const cellDiagramBlock = source.slice(source.indexOf("const cellDiagrams = {"), source.indexOf("const cellHighlightShapes = {"));

assert.ok(source.includes('prep: "assets/owl-cell-structure-prep-scan.webp"'));
assert.ok(fs.existsSync(path.join(root, "assets", "owl-cell-structure-prep-scan.webp")));
assert.ok(!source.includes("owl-basic-unit-micro-guide"));
assert.ok(!source.includes("owl-basic-unit-cell-scan"));
assert.ok(!brief.includes("cellStructureOwlAssets"), "brief must not render an owl");
assert.deepEqual(checkpoint1Ids, ["nucleus", "mitochondria", "chloroplast", "vacuole"]);
assert.ok(!checkpoint1Catalog.includes("prompt:"), "checkpoint1 must use the visual target rather than reveal a per-target prompt");
assert.ok(!cellDiagramBlock.includes('id: "membrane"'), "checkpoint1 diagram data must not keep membrane as a visual target");
assert.ok(!cellDiagramBlock.includes('id: "cytoplasm"'), "checkpoint1 diagram data must not keep cytoplasm as a visual target");
assert.ok(!cellDiagramBlock.includes('id: "wall"'), "checkpoint1 diagram data must not keep wall as a visual target");
assert.ok(source.includes('return ["chloroplast", "vacuole"].includes(structureId) ? "plant" : "animal"'));
assert.ok(source.includes('structureTransitionNotice: ""'));
assert.ok(source.includes("動物細胞辨識完成，正在切換植物細胞。"));
assert.ok(!source.includes('class="tab-button cell-tab'));
assert.ok(source.includes('data-highlight-target="${selectedId}"'));
assert.ok(source.includes('data-overlay-mode="color-reveal"'));
assert.ok(source.includes('class="cell-color-reveal-mask"'));
assert.ok(source.includes('class="cell-color-reveal-image"'));
assert.ok(source.includes('mask="url(#${maskId})"'));
assert.ok(source.includes('data-reveal-exclusion-count="${exclusions.length}"'));
assert.ok(source.includes('return `<img class="cell-image cell-image-grayscale"'));
assert.ok(!source.includes("cellArrowTargets"));
assert.ok(!source.includes("marker-end="));
assert.ok(source.includes('cell-highlight-layer halo-layer'));
assert.ok(source.includes('cell-highlight-layer core-layer'));
assert.ok(source.includes('const CHECKPOINT1_CONCEPT_EXP = 140'));
assert.ok(source.includes('const CHECKPOINT1_REVISION_EXP = 70'));
assert.ok(!source.includes("140 / checkpoint1Items.length"));
assert.ok(!source.includes("70 / checkpoint1Items.length"));
assert.ok(source.includes('mitochondria: "mitochondrion"'));
assert.ok(source.includes('vacuole: "large_vacuole"'));
assert.ok(source.includes('target_count: checkpoint1Items.length'));
assert.ok(source.includes('cell_structure_required_target_count: checkpoint1Items.length'));
assert.ok(source.includes('cell_structure_completed_target_count: completedTargetCount'));
assert.ok(source.includes('cell_structure_missing_target_count: checkpoint1Items.length - completedTargetCount'));
assert.ok(source.includes('exp_type: "evidence_only"'));
assert.ok(source.includes('exp_awarded: 0'));
const vacuoleShapes = source.slice(source.indexOf("vacuole: [", source.indexOf("const cellHighlightShapes")), source.indexOf("chloroplast: [", source.indexOf("const cellHighlightShapes")));
assert.equal((vacuoleShapes.match(/type:\s*"path"/g) || []).length, 1, "vacuole must use one merged reveal path");
assert.equal((vacuoleShapes.match(/type:\s*"ellipse"/g) || []).length, 0, "vacuole must not use overlapping ellipse masks");
const mitochondriaShapes = source.slice(source.indexOf("mitochondria: [", source.indexOf("const cellHighlightShapes")), source.indexOf("plant: {", source.indexOf("const cellHighlightShapes")));
assert.equal((mitochondriaShapes.match(/type:\s*"path"/g) || []).length, 4, "each mitochondrion must use its own fitted reveal path");
assert.equal((mitochondriaShapes.match(/type:\s*"ellipse"/g) || []).length, 0, "mitochondria must not use coarse ellipse masks");
const chloroplastShapes = source.slice(source.indexOf("chloroplast: [", source.indexOf("const cellHighlightShapes")), source.indexOf("const cellRevealExclusions"));
assert.equal((chloroplastShapes.match(/type:\s*"path"/g) || []).length, 3, "each chloroplast must use its own fitted reveal path");
assert.equal((chloroplastShapes.match(/type:\s*"ellipse"/g) || []).length, 0, "chloroplasts must not use coarse ellipse masks");
assert.ok(scan.includes("cellStructureOwlAssets.prep"));
assert.ok(scan.indexOf("prep-owl-hero") < scan.indexOf("progress-steps"));
assert.ok(reflection.includes("cellStructureOwlAssets.report"));
assert.ok(reflection.includes('class="bq-report-assistant report-owl-hero"'));
assert.ok(result.includes("cellStructureOwlAssets.result"));
assert.ok(source.includes('directPath.startsWith("shared-assets/")'));
assert.ok(source.includes("title-01-trainee_investigator-${titleAvatarGender()}.webp"));
assert.ok(source.includes("window.confirm"));
const hotspotRule = styles.match(/\.cell-hotspot \{([\s\S]*?)\n\}/)?.[1] || "";
assert.ok(hotspotRule.includes("border: 2px solid transparent"));
assert.ok(hotspotRule.includes("background: transparent"));
assert.ok(hotspotRule.includes("box-shadow: none"));
assert.ok(styles.includes(".cell-highlight-halo"));
assert.ok(styles.includes(".cell-image-grayscale"));
assert.ok(styles.includes("grayscale(1)"));
assert.ok(styles.includes(".cell-color-reveal-image"));
assert.ok(styles.includes("stroke-width: 4"));
assert.ok(styles.includes(".cell-highlight-core"));
assert.ok(styles.includes("fill: none"));
assert.ok(styles.includes("stroke-width: 1.8"));
assert.ok(!styles.includes(".cell-target-arrow-outline"));
assert.ok(source.includes('const VERSION = "20260731-cell-structure-submitted-retry-ia-v1"'));
assert.ok(source.includes('const QUESTION_VERSION = "20260720-cell-structure-canonical-v1"'));
assert.ok(!source.includes("question_version: VERSION"), "cache VERSION must not be used as backend question_version");
assert.ok(index.includes("styles.css?v=20260731-cell-structure-submitted-retry-ia-v1"));
assert.ok(index.includes("app.js?v=20260731-cell-structure-submitted-retry-ia-v1"));
assert.ok(source.includes("function resetForRelogin()"));
assert.ok(source.includes('data-relogin-action="true"'));
assert.ok(source.includes("function renderResultBadges(result)"));
assert.ok(!source.includes("function renderBadgeCatalog("), "legacy full unit badge catalog renderer must be removed");
assert.ok(!source.includes('data-bq-unit-achievements="true"'), "achievements must not render a local unit badge wall");
assert.ok(source.includes('async function startAttemptSession(studentId)'));
assert.ok(source.includes('startData.verification_mode !== "server_verified"'));
assert.ok(source.includes('startData.question_version !== QUESTION_VERSION'));
assert.ok(source.includes('後台版本尚未更新，請通知老師。'));
assert.ok(source.includes('async function flushHintEvents'));
assert.ok(source.includes('throw new Error("hint_event_sync_failed")'));
assert.ok(source.includes('if (attempt.student?.is_guest) return { ok: true, verification_status: "local_guest" };'));
assert.ok(source.includes("window.__cellStructureTest"));
const canonicalMetaBlock = source.slice(source.indexOf("const canonicalQuestionMeta = {"), source.indexOf("const checkpoint2CanonicalByLocalId"));
assert.equal((canonicalMetaBlock.match(/q\d+:/g) || []).length, 13, "cell_structure must expose q01-q13 canonical metadata");
assert.ok(canonicalMetaBlock.includes('q01: { local_id: "visual_targets", type: "mapping"'));
assert.ok(source.includes('q01: Object.fromEntries(Object.entries(CHECKPOINT1_TARGET_LOG_IDS)'));
assert.ok(source.includes('question_logs: canonicalQuestionLogs()'));
assert.ok(source.includes('raw_answers_json: JSON.stringify(rawAnswers)'));
assert.ok(source.includes('cell_structure_target_logs_json: JSON.stringify(buildCheckpoint1QuestionLogs())'));
const q01Forbidden = source.slice(source.indexOf("const CHECKPOINT1_TARGET_LOG_IDS = {"), source.indexOf("};", source.indexOf("const CHECKPOINT1_TARGET_LOG_IDS = {")));
assert.ok(!q01Forbidden.includes("membrane"), "cell membrane must not return as a q01 target id");
assert.ok(!q01Forbidden.includes("cytoplasm"), "cytoplasm must not return as a q01 target id");
assert.ok(!q01Forbidden.includes("wall"), "cell wall must not return as a q01 target id");

console.log("prototype-cell-structure owl hook checks passed");
